select * from customer 

--Q1 total revenue generated by male and female customer?
select sum(Purchase_Amount_USD), gender from customer  group by gender

--Q2 customer used discount but still payed more then avg amount
select customer_id, Discount_Applied from customer where Discount_Applied ='Yes' 
and [Purchase_Amount_USD] > (select avg(Purchase_Amount_USD) from customer)

--Q3 top 5 products with highest avg rating
select top 6 [Category], avg(review_rating) as avg_rating 
from customer group by category order by avg_rating desc


--Q4 avg purchase amt btw standard and express shipping
select shipping_type, avg(Purchase_Amount_USD) as avg_purchase from customer 
where shipping_type in ('standard', 'express')
group by shipping_type 

--Q5  do subscribed customers spend more? Compare avg spend and total revenue 
--btw subscribers  and non-subscribers?
select [Subscription_Status],avg([Purchase_Amount_USD]) as avg_spend,
sum([Purchase_Amount_USD]) as total_revenue from customer 
group by Subscription_Status

--Q6 which 5 products have highest % with dicount applied?

select category, 100.0 * sum(case when Discount_Applied = 'Yes' then 1 else 0 end )
/ count(*) as discount_percentage 
from customer
group by category 
order by Discount_percentage  desc 

--Q7 segment customers into new, returning, and loyal based on their total no. of previous purchases, 
--and show the count of each segment?
select
case 
when Previous_Purchases = 0 then 'New'
when Previous_Purchases between 1 and 4 then 'Returning'
else 'Loyal'
end as Customer_segment,
count(*) as total_customers
from customer group by 
case 
when Previous_Purchases = 0 then 'New'
when Previous_Purchases between 1 and 4 then 'Returning'
else 'Loyal'
end

--Q8 3 most purchased products within each category.
select  [Category],[Item_Purchased],Purchase_count
from (
select category, [Item_Purchased],
count(*) as Purchase_count, 
row_number() over( partition by category order by 
count(*) desc
)
 as rn from customer group by category, Item_Purchased )
 as Ranked where rn <= 3;

 --Q9 are custmers who are repeat buyers (more than 5 previous purchase) also likely to subscribe ?
 SELECT 
    Subscription_Status,
    CASE 
        WHEN Previous_Purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS Buyer_Type,
    COUNT(*) AS Total_Customers
FROM customer
GROUP BY 
    Subscription_Status,
    CASE 
        WHEN Previous_Purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END;


--Q10 revenue contribution of each age group .
select 
case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 50 then '36-50'
else '50+'
end as age_group, 
sum(Purchase_Amount_USD) as total_revenue

FROM customer
GROUP BY 
    CASE 
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END;

    select age_group from customer